# -*- coding: utf-8 -*-
"""Historical Records data set

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LPBTGdQxvXLZ8r8XKBkOEBE9I-wPwzkL
"""

import numpy as np
import random
import json

# --- Datasets/Constants derived *Primarily* from Historical Patient Records (D1) ---
AVG_LOS_HIGH_PRIORITY = 48  # Average Length of Stay for High Priority Patients (D1)
PATIENT_PRIORITY_DISTRIBUTION = [0.15, 0.40, 0.45] # P1, P2, P3 (D1)
HISTORICAL_WAIT_FACTOR = 8.5 # Baseline complexity of scheduling (D1)
WEIGHT_WAIT_TIME = 0.40 # Weighting (D4 - Public Health) is fixed here for simplicity

# --- Core Algorithm Functions ---

def run_ga_with_historical(wait_factor, workload_var, capacity_vio):
    """
    GA uses D1 to define the main objective: minimizing wait time based on HISTORICAL_WAIT_FACTOR.
    """
    total_cost = (WEIGHT_WAIT_TIME * wait_factor) + (0.35 * workload_var) + (0.25 * capacity_vio)
    fitness = 1.0 / (1.0 + total_cost)
    return f"GA Fitness: {fitness:.4f} (Driven by D1 wait factor)"

def run_rl_with_historical(current_queue):
    """
    RL Agent uses D1 to inform the reward function: heavily penalizing increased queue size.
    """
    # Simulate a reduction in queue by prioritizing a P1 patient (based on D1 distribution)
    reward = 10.0 if current_queue > 0 and random.random() < PATIENT_PRIORITY_DISTRIBUTION[0] else -5.0
    return f"RL Reward: {reward:.1f} (Informed by D1 priority mix)"

def run_gan_with_historical(time_series_data):
    """
    GAN uses D1 as the training basis to learn the historical patient arrival sequence patterns.
    """
    # Simulate generating a synthetic sequence that matches the D1 distribution
    synthetic_inflow = [int(np.round(np.mean(time_series_data) * random.uniform(0.5, 1.5))) for _ in range(3)]
    return f"GAN Output: Synthetic Inflow Sequence (First 3hrs): {synthetic_inflow} (Matches D1 pattern)"

def run_llm_with_historical(top_diagnoses):
    """
    LLM uses D1 to predict care pathways and estimate future LOS based on past diagnoses.
    """
    prompt_fragment = f"Historical Context (D1): Top Diagnoses: {', '.join(top_diagnoses)}. Average LOS P1: {AVG_LOS_HIGH_PRIORITY} hrs. Predict resource needs."
    return f"LLM Prompt Fragment: '{prompt_fragment[:70]}...' (Focused on D1 metrics)"

# --- Execution Logic: Run All Algorithms At Once ---

if __name__ == "__main__":
    print("--- Program 1: Historical Patient Records (D1) Driver ---")

    # 1. Simulate Inputs from D1 (Historical Patient Records)
    # The algorithms still need *some* input from D2, D3, D4 for a complete run,
    # but D1 is the primary focus.

    # D1 Focus Variables
    d1_wait_factor = HISTORICAL_WAIT_FACTOR
    d1_queue = 5
    d1_time_series_data = [2, 4, 6, 3, 5, 7] # Sample historical inflow
    d1_top_diagnoses = ["Cardio", "Trauma", "Infection"]

    # D2, D3, D4 Placeholder Inputs (Needed for the full algorithm signature)
    d3_workload_variance = 2.1
    d2_capacity_violations = 0.5

    print("\n--- Running All Four Algorithms using D1-Derived Parameters ---")

    # GA
    ga_result = run_ga_with_historical(d1_wait_factor, d3_workload_variance, d2_capacity_violations)
    print(f"1. Genetic Algorithm: {ga_result}")

    # RL
    rl_result = run_rl_with_historical(d1_queue)
    print(f"2. Reinforcement Learning: {rl_result}")

    # GAN
    gan_result = run_gan_with_historical(d1_time_series_data)
    print(f"3. Generative AI (GAN): {gan_result}")

    # LLM
    llm_result = run_llm_with_historical(d1_top_diagnoses)
    print(f"4. Generative AI (LLM): {llm_result}")

    print("\nConclusion: All algorithms successfully process and utilize data primarily derived from Historical Patient Records (D1) to inform their core functions.")

